package messaging

const GET = "GET"
const GET_RESPONSE = "GET_RESPONSE"

const ADD = "ADD"
const ADD_RESPONSE = "ADD_RESPONSE"

const ADD_ATOMIC = "ADD_ATOMIC"

const BRACHA_BROADCAST = "BRACHA_BROADCAST"
const BRACHA_BROADCAST_INIT = "BRACHA_BROADCAST_INIT"
const BRACHA_BROADCAST_ECHO = "BRACHA_BROADCAST_ECHO"
const BRACHA_BROADCAST_VOTE = "BRACHA_BROADCAST_VOTE"
