#!/bin/bash

while true; do
    echo Waiting for clients to finish...
    # Get the list of nodes under the [clients-automated] tag from a remote machine
    nodes=($(awk '/^\[clients-automated\]/{flag=1;next}/^\[/{flag=0}flag{print $1}' hosts))
    # Check if every node is done with the process "2-Atomic-Adds"
    done_count=0
    for node in $nodes; do
        ssh $node "pgrep 2-Atomic-Adds > /dev/null && echo \"Node $node is done\" || echo \"Node $node is not done\""
    done | grep -v "Node.*is done" || ((done_count++))

    # If every node is done, run the second script
    if [[ $done_count -eq 0 ]]; then
        rm -rf results
        mkdir results # add experiemtn identifier
        for num in {0..30}; do
            scp loukis@node$num:/users/loukis/Thesis/BFT-Distributed-G-Set-Remote/client/experiment_results.txt /users/loukis/Thesis/BFT-Distributed-G-Set-Remote/results/node$num.txt
            scp loukis@node$num:/users/loukis/Thesis/BFT-Distributed-G-Set-Remote/server/experiment_results.txt /users/loukis/Thesis/BFT-Distributed-G-Set-Remote/results/node$num.txt
        done
        break
    fi

    sleep 5 # wait for 5 seconds before running the first script again
done
