package messaging

const GET = "GET"
const GET_RESPONSE = "GET_RESPONSE"

const ADD_ATOMIC = "ADD_ATOMIC"
const ADD_ATOMIC_RESPONSE = "ADD_ATOMIC_RESPONSE"

const ADD = "ADD"
const ADD_RESPONSE = "ADD_RESPONSE"
